CREATE SCHEMA EC2_SI1N;

USE EC2_SI1N;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF VARCHAR(11) PRIMARY KEY,
PASS_NOME VARCHAR(45) NOT NULL,
PASS_TELEFONE VARCHAR(15) NOT NULL,
PASS_RUA VARCHAR(45) NOT NULL,
PASS_NUMRUA INT,
PASS_BAIRRO VARCHAR(45) NOT NULL,
PASS_CIDADE VARCHAR(45) NOT NULL,
PASS_ESTADO VARCHAR(45) NOT NULL,
PASS_PAIS VARCHAR(30) NOT NULL,
PASS_CODPOSTAL VARCHAR(10) NOT NULL,
PASS_EMAIL VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROPORTO_COD INT PRIMARY KEY,
AEROPORTO_NOME VARCHAR(20) NOT NULL,
AEROPORTO_LOCAL VARCHAR(20) NOT NULL,
AEROPORTO_PAIS VARCHAR (20) NOT NULL,
AEROPORTO_LONGITUDE INT,
AEROPORTO_LATITUDE INT
);

CREATE TABLE IF NOT EXISTS AERONAVES(
AERONAVE_PREFIXO VARCHAR(10) PRIMARY KEY,
AERONAVE_MODELO VARCHAR(20) NOT NULL,
AERONAVE_ANOFABRIC YEAR NOT NULL,
AERONAVE_CAPACIDADE INT,
AERONAVE_FABRICANTE VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONÁRIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_FUNCAO VARCHAR(45) NOT NULL,
FUNC_NOME VARCHAR(45) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS(
VOO_CODIGO INT PRIMARY KEY,
DATA_HORA_ORIGEM DATE NOT NULL,
DATA_HORA_DESTINO DATE NOT NULL,
AEROPORTO_ORIGEM INT NOT NULL,
FOREIGN KEY (AEROPORTO_ORIGEM) REFERENCES AEROPORTOS(AEROPORTO_COD),
AEROPORTO_DESTINO INT NOT NULL,
FOREIGN KEY (AEROPORTO_DESTINO) REFERENCES AEROPORTOS(AEROPORTO_COD),
AERONAVE_PREFIXO VARCHAR(10) NOT NULL,
FOREIGN KEY (AERONAVE_PREFIXO) REFERENCES AERONAVES(AERONAVE_PREFIXO)
);

CREATE TABLE IF NOT EXISTS RESERVAS(
PASS_CPF INT,
VOO_COD INT, 
PRIMARY KEY(PASS_CPF, VOO_COD),
FOREIGN KEY(PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF),
FOREIGN KEY(VOO_COD) REFERENCES VOOS(VOO_COD)
);

CREATE TABLE IF NOT EXISTS EQUIPES(
FUNC_ID INT,
VOO_COD INT,
PRIMARY KEY(FUNC_ID, VOO_COD),
FOREIGN KEY(FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID),
FOREIGN KEY(VOO_COD) REFERENCES VOOS(VOO_COD)
);
